Repository WildCodeSchool-2024-02/PHP-REM-POEC-05-Gazette-Sorciers, pull requests merged in 2024-07, with the labels that each got.

#2 Feature/adding database
  composer.lock
  database.sql
Labels: REVIEWED

#6 S01 navbar
  .github/workflows/main.yml
  composer.json
  composer.lock
  public/assets/css/_navbar.css
  public/assets/images/logo.png
  public/assets/images/logo1.png
  src/View/Home/_navbar.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#7 S01 listing category
  composer.lock
  database.sql
  public/assets/css/_categories.css
  public/assets/css/style.css
  src/Controller/CategoryController.php
  src/Controller/HomeController.php
  src/Model/CategoryManager.php
  src/View/Categories/_form.html.twig
  src/View/Categories/add.html.twig
  src/View/Categories/edit.html.twig
  src/View/Categories/index.html.twig
  src/View/Categories/show.html.twig
  src/View/Home/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/routes.php
  tests/controllers/CategoryControllerTest.php
  tests/models/CategoryManagerTest.php
Labels: REVIEWED

#9 S01 login
  phpunit.xml
  public/assets/css/_auth.css
  src/Controller/AuthController.php
  src/Controller/RegisterController.php
  src/Model/UserManager.php
  src/View/Auth/login.html.twig
  src/View/Auth/register.html.twig
  src/routes.php
Labels: REVIEWED

#10 modification main github/workflows
  .github/workflows/main.yml
  public/assets/css/_auth.css
  public/assets/css/_footer.css
  public/assets/css/_form.css
  public/assets/css/_navbar.css
  public/assets/css/style.css
  src/View/Auth/login.html.twig
  src/View/Auth/register.html.twig
  src/View/Categories/add.html.twig
  src/View/layout.html.twig
Labels: CHANGES REQUESTED, REVIEWED

#13 S02 modify authentication
  .github/workflows/main.yml
  src/Controller/AuthController.php
  src/Controller/UserController.php
  src/Model/UserManager.php
  src/routes.php
Labels: REVIEWED

#12 delete AuthController,RegisterController/create UserController✅
  src/Controller/AuthController.php
  src/Controller/UserController.php
  src/routes.php
Labels: CHANGES REQUESTED

#15 S02 session category
  src/Controller/AbstractController.php
  src/Controller/CategoryController.php
  src/Controller/UserController.php
  src/Model/PrivilegeManager.php
  src/Model/UserManager.php
  src/View/Categories/edit.html.twig
  src/routes.php
Labels: CHANGES REQUESTED, REVIEWED

#20 show users ✅/ delete user ✅
  public/assets/css/_modal.css
  public/assets/css/_table.css
  public/assets/css/_users.css
  public/assets/js/modal.js
  src/Controller/UserController.php
  src/Model/UserManager.php
  src/View/Home/_navbar.html.twig
  src/View/Users/_modal.html.twig
  src/View/Users/index.html.twig
  src/View/Users/show.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#23 S03 golden snitch
  forumprojet2.sql
  public/assets/css/_goldensnitch.css
  public/assets/css/editProfile.css
  public/assets/css/profile.css
  public/assets/images/giphy.gif
  public/assets/images/pp.jpg
  public/assets/js/snitch_script.js
  src/Controller/ProfileController.php
  src/Model/UserManager.php
  src/View/Home/_navbar.html.twig
  src/View/UserProfile/_form.html.twig
  src/View/UserProfile/editProfile.html.twig
  src/View/UserProfile/profile.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#25 S03 page contact
  public/assets/css/_form.css
  public/assets/css/_mod.css
  public/assets/js/mod.js
  src/Controller/ContactController.php
  src/Controller/ProfileController.php
  src/Model/ContactManager.php
  src/View/Contact/_form.html.twig
  src/View/Contact/_modal.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/_navbar.html.twig
  src/View/Users/index.html.twig
  src/routes.php
Labels: REVIEWED

#27 S03 session profile
  composer.lock
  public/assets/js/snitch_script.js
  src/Controller/ProfileController.php
  src/View/Auth/login.html.twig
  src/View/Home/_navbar.html.twig
  src/View/UserProfile/profile.html.twig
Labels: REVIEWED

#28 S02 comments
  public/assets/css/_auth.css
  public/assets/css/_comment.css
  public/assets/css/_form.css
  src/Controller/CommentController.php
  src/Model/AbstractManager.php
  src/Model/CommentManager.php
  src/View/Auth/login.html.twig
  src/View/Auth/register.html.twig
  src/View/Categories/add.html.twig
  src/View/Home/index.html.twig
  src/View/Topic/_form.html.twig
  src/View/comments/_form.html.twig
  src/View/comments/add.html.twig
  src/View/comments/edit.html.twig
  src/View/comments/index.html.twig
  src/View/comments/show.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#29 Fix/s01 topics
  public/assets/css/_footer.css
  public/assets/css/style.css
  public/assets/css/topic.css
  public/upload/2024-07-12-09-31-00-f.png
  public/upload/2024-07-12-09-36-18-f.png
  src/View/Home/_footer.html.twig
  src/View/Home/index.html.twig
  src/View/Home/main.html.twig
  src/View/Topic/index.html.twig
  src/View/Topic/show.html.twig
  src/View/comments/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#30 S04 page legal notice
  public/assets/css/notice.css
  src/Controller/StaticPageController.php
  src/View/Home/_navbar.html.twig
  src/View/Notice/index.html.twig
  src/View/Users/_modal.html.twig
  src/routes.php
Labels: REVIEWED

#31 Ajout Page About
  public/assets/css/staticPage.css
  src/Controller/StaticPageController.php
  src/View/About/index.html.twig
  src/View/Home/_navbar.html.twig
  src/View/Notice/index.html.twig
  src/routes.php
Labels: REVIEWED

#32 quelques correction css et affichage page gestion users
  public/assets/css/_form.css
  public/assets/css/style.css
  src/View/Auth/login.html.twig
  src/View/Auth/register.html.twig
  src/View/Categories/show.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/_footer.html.twig
  src/View/Users/_modal.html.twig
  src/View/Users/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#33 encapsulastion logique vérification admin
  public/assets/css/_footer.css
  public/assets/css/_mod.css
  public/assets/css/style.css
  src/Controller/AbstractController.php
  src/Controller/CategoryController.php
  src/Controller/ContactController.php
  src/Controller/ProfileController.php
  src/Controller/UserController.php
  src/Model/PrivilegeManager.php
  src/Model/UserManager.php
  src/View/Auth/register.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/_footer.html.twig
  src/View/Home/_navbar.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#34 petite correction import de js
  src/View/Contact/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#35 S04 search bar
  public/assets/css/_navbar.css
  public/assets/css/editProfile.css
  public/assets/js/search.js
  src/Controller/SearchController.php
  src/Model/SearchManager.php
  src/View/Home/_navbar.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#36 S03 comments css
  public/assets/css/_comment.css
  public/upload/2024-07-11-10-22-13-dtb.png
  public/upload/2024-07-12-09-31-00-f.png
  public/upload/2024-07-12-09-36-18-f.png
  src/Controller/CommentController.php
  src/Controller/TopicController.php
  src/Model/CommentManager.php
  src/View/Topic/show.html.twig
  src/View/comments/_comment.html.twig
  src/View/comments/_form.html.twig
  src/View/comments/show.html.twig
  src/routes.php
Labels: REVIEWED

#37 S04 banner
  forumprojet2.sql
  public/assets/css/_categories.css
  public/assets/css/_navbar.css
  public/assets/css/profile.css
  public/assets/css/style.css
  public/assets/images/banner-default.jpg
  public/assets/images/banner4.jpg
  src/View/Categories/index.html.twig
  src/View/Categories/show.html.twig
  src/View/Home/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#38 Ajout des cookies
  public/assets/css/_cookies.css
  public/assets/images/cookie_icon.png
  public/assets/js/cookiesModal.js
  src/Controller/UserController.php
  src/View/Cookies/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#40 Fix/s04 cat css
  public/assets/css/_categories.css
  public/assets/images/catégories.png
  public/assets/images/derniers-messages.png
  src/View/Categories/index.html.twig
  src/View/Categories/show.html.twig
  src/View/Home/index.html.twig
Labels: REVIEWED

#41 Fix/s04 cat css
  public/assets/css/_categories.css
  public/assets/css/_navbar.css
  public/assets/css/addCategory.css
  src/View/Categories/_form.html.twig
  src/View/Categories/add.html.twig
  src/View/Home/_navbar.html.twig
Labels: REVIEWED

#42 S03 comments - topics - navbar css
  public/assets/css/_comment.css
  public/assets/css/_navbar.css
  src/View/Home/_navbar.html.twig
  src/View/comments/_comment.html.twig
Labels: REVIEWED

#43 Fix/s04 cat css
  src/Controller/AbstractController.php
  src/Controller/ProfileController.php
  src/Controller/UserController.php
  src/Model/UserManager.php
  src/View/Home/_navbar.html.twig
  src/View/UserProfile/profile.html.twig
  src/routes.php
Labels: CONFLICTS RESOLVED, REVIEWED
